import argparse
import csv
from pathlib import Path
from typing import List


EXPECTED = ["inversor", "bateria", "cargador_ev", "compatible"]


def normalize_bool(value: str) -> str:
    lower = (value or "").strip().lower()
    return "true" if lower in {"1", "true", "si", "sí", "yes", "compatible"} else "false"


def esc(value: str) -> str:
    return value.replace("'", "''")


def main() -> None:
    parser = argparse.ArgumentParser(description="Convierte CSV de compatibilidad (OCR/manual) a SQL upsert.")
    parser.add_argument("--input", required=True, help="CSV con columnas: inversor,bateria,cargador_ev,compatible")
    parser.add_argument("--output", default="data/queries/generated/compatibilidad_inversor_bateria_cargador_ev.generated.sql")
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        raise FileNotFoundError(f"Input not found: {input_path}")

    rows: List[str] = []
    with input_path.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        missing = [c for c in EXPECTED if c not in (reader.fieldnames or [])]
        if missing:
            raise RuntimeError(f"Missing CSV columns: {', '.join(missing)}")

        for row in reader:
            inversor = (row.get("inversor") or "").strip()
            bateria = (row.get("bateria") or "").strip()
            cargador = (row.get("cargador_ev") or "").strip()
            compatible = normalize_bool(row.get("compatible") or "")
            if not inversor or not bateria or not cargador:
                continue
            rows.append(
                f"  ('{esc(inversor)}', '{esc(bateria)}', '{esc(cargador)}', {compatible})"
            )

    if not rows:
        raise RuntimeError("No valid rows found in input CSV")

    sql = "\n".join(
        [
            "-- Auto-generated by scripts/python/compatibility_csv_to_sql.py",
            "insert into compatibilidad_inversor_bateria_cargador_ev_es (inversor, bateria, cargador_ev, compatible)",
            "values",
            ",\n".join(rows),
            "on conflict (inversor, bateria, cargador_ev) do update set",
            "  compatible = excluded.compatible,",
            "  updated_at = now();",
            "",
        ]
    )

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(sql, encoding="utf-8")

    print(f"[OK] SQL generado: {out}")
    print(f"[OK] Filas validas: {len(rows)}")


if __name__ == "__main__":
    main()
