import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List
from urllib.parse import urlencode
from urllib.request import Request, urlopen

ESIOS_BASE = "https://api.esios.ree.es/indicators"


def fetch_indicator_values(token: str, indicator_id: str, start_date: str, end_date: str, timezone: str) -> List[Dict[str, Any]]:
    params = {
        "start_date": start_date,
        "end_date": end_date,
        "time_trunc": "day",
    }
    url = f"{ESIOS_BASE}/{indicator_id}?{urlencode(params)}"

    req = Request(url)
    req.add_header("Accept", "application/json; application/vnd.esios-api-v1+json")
    req.add_header("Content-Type", "application/json")
    req.add_header("Host", "api.esios.ree.es")
    req.add_header("x-api-key", token)

    with urlopen(req, timeout=45) as resp:
        payload = json.loads(resp.read().decode("utf-8", errors="replace"))

    values = payload.get("indicator", {}).get("values", [])
    normalized: List[Dict[str, Any]] = []
    for row in values:
        dt = row.get("datetime") or row.get("datetime_utc")
        if not dt:
            continue

        try:
            # Example: 2026-03-01T00:00:00.000+01:00
            iso_dt = datetime.fromisoformat(dt.replace("Z", "+00:00"))
            date_str = iso_dt.date().isoformat()
        except Exception:
            continue

        value = row.get("value")
        if value is None:
            continue

        # ESIOS suele venir en EUR/MWh; convertimos a EUR/kWh.
        eur_kwh = float(value) / 1000.0
        normalized.append({"date": date_str, "eur_kwh": eur_kwh})

    # Consolidamos por fecha (media diaria si vinieran multiples entradas).
    agg: Dict[str, List[float]] = {}
    for r in normalized:
        agg.setdefault(r["date"], []).append(r["eur_kwh"])

    output: List[Dict[str, Any]] = []
    for date_key in sorted(agg.keys()):
        vals = agg[date_key]
        output.append({"date": date_key, "eur_kwh": sum(vals) / len(vals)})

    return output


def build_sql(records: List[Dict[str, Any]], tarifa_codigo: str, tarifa_nombre: str) -> str:
    lines: List[str] = []
    lines.append("-- Auto-generated by scripts/python/esios_to_sql.py")
    lines.append(
        "insert into tarifas_electricas (codigo, nombre, tipo_consumidor, discriminacion_horaria, peaje_acceso, comercializadora, activa)\n"
        f"values ('{tarifa_codigo}', '{tarifa_nombre}', 'domestico', true, '2.0TD', 'ESIOS', true)\n"
        "on conflict (codigo) do update set\n"
        "  nombre = excluded.nombre,\n"
        "  tipo_consumidor = excluded.tipo_consumidor,\n"
        "  discriminacion_horaria = excluded.discriminacion_horaria,\n"
        "  peaje_acceso = excluded.peaje_acceso,\n"
        "  comercializadora = excluded.comercializadora,\n"
        "  activa = excluded.activa,\n"
        "  updated_at = now();"
    )

    if not records:
        return "\n\n".join(lines) + "\n"

    values = []
    for r in records:
        p = r["eur_kwh"]
        values.append(
            f"  ((select id from tarifas_electricas where codigo = '{tarifa_codigo}'), 'nacional', '{r['date']}', {p:.6f}, {p:.6f}, {p:.6f}, {p:.6f}, 'ESIOS')"
        )

    lines.append(
        "insert into precios_electricidad (tarifa_id, ambito, fecha, precio_kwh_eur, precio_punta_eur, precio_llano_eur, precio_valle_eur, fuente)\n"
        "values\n"
        + ",\n".join(values)
        + "\non conflict do nothing;"
    )

    return "\n\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Extrae precios ESIOS y genera SQL para precios_electricidad.")
    parser.add_argument("--token", required=True, help="API key de ESIOS")
    parser.add_argument("--indicator-id", default="10391", help="Indicador ESIOS (por defecto: 10391)")
    parser.add_argument("--start-date", required=True, help="YYYY-MM-DD")
    parser.add_argument("--end-date", required=True, help="YYYY-MM-DD")
    parser.add_argument("--timezone", default="Europe/Madrid")
    parser.add_argument("--tarifa-codigo", default="esios-pvpc")
    parser.add_argument("--tarifa-nombre", default="PVPC ESIOS")
    parser.add_argument("--output", default="data/queries/generated/precios_electricidad_esios.generated.sql")
    args = parser.parse_args()

    records = fetch_indicator_values(
        token=args.token,
        indicator_id=args.indicator_id,
        start_date=args.start_date,
        end_date=args.end_date,
        timezone=args.timezone,
    )

    sql = build_sql(records, tarifa_codigo=args.tarifa_codigo, tarifa_nombre=args.tarifa_nombre)
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(sql, encoding="utf-8")

    print(f"[OK] SQL generado: {out}")
    print(f"[OK] Dias procesados: {len(records)}")


if __name__ == "__main__":
    main()
