import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Optional


def esc(value: str) -> str:
    return value.replace("'", "''")


def to_num(value: Any) -> Optional[float]:
    if value is None:
        return None
    try:
        return float(str(value).replace(",", "."))
    except Exception:
        return None


def to_int(value: Any) -> Optional[int]:
    if value is None:
        return None
    try:
        return int(float(str(value).replace(",", ".")))
    except Exception:
        return None


def load_records(path: str) -> List[Dict[str, Any]]:
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    if isinstance(payload, dict) and "items" in payload:
        payload = payload["items"]
    if not isinstance(payload, list):
        raise RuntimeError("Input JSON must be a list or an object with 'items'.")
    return payload


def build_sql(records: List[Dict[str, Any]]) -> str:
    ibi_rows: List[str] = []
    icio_rows: List[str] = []

    for rec in records:
        municipio = (rec.get("municipio") or "").strip()
        provincia = (rec.get("provincia") or "").strip()
        condiciones = (rec.get("condiciones") or rec.get("notas") or "Pendiente de validacion.").strip()

        if not municipio or not provincia:
            continue

        ibi_pct = to_num(rec.get("ibi_pct"))
        ibi_anos = to_int(rec.get("ibi_anos"))
        icio_pct = to_num(rec.get("icio_pct"))
        icio_anos = to_int(rec.get("icio_anos"))

        if ibi_pct is not None:
            ibi_rows.append(
                f"  ('{esc(municipio)}', '{esc(provincia)}', {ibi_pct:.2f}, {ibi_anos if ibi_anos is not None else 0}, '{esc(condiciones)}')"
            )

        if icio_pct is not None:
            icio_rows.append(
                f"  ('{esc(municipio)}', '{esc(provincia)}', {icio_pct:.2f}, {icio_anos if icio_anos is not None else 0}, '{esc(condiciones)}')"
            )

    if not ibi_rows and not icio_rows:
        raise RuntimeError("No valid records found for IBI/ICIO.")

    parts: List[str] = []
    parts.append("-- Auto-generated by scripts/python/ibi_icio_to_sql.py")

    parts.append(
        """
create table if not exists bonificaciones_icio_municipios_es (
  id bigserial primary key,
  municipio text not null,
  provincia text not null,
  porcentaje_bonificacion numeric(5,2) not null check (porcentaje_bonificacion between 0 and 100),
  duracion_anos smallint not null check (duracion_anos between 0 and 50),
  condiciones text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (municipio, provincia)
);
""".strip()
    )

    if ibi_rows:
        parts.append(
            "insert into bonificaciones_ibi_municipios_es (municipio, provincia, porcentaje_bonificacion, duracion_anos, condiciones)\nvalues\n"
            + ",\n".join(ibi_rows)
            + "\non conflict (municipio, provincia) do update set\n"
            + "  porcentaje_bonificacion = excluded.porcentaje_bonificacion,\n"
            + "  duracion_anos = excluded.duracion_anos,\n"
            + "  condiciones = excluded.condiciones,\n"
            + "  updated_at = now();"
        )

    if icio_rows:
        parts.append(
            "insert into bonificaciones_icio_municipios_es (municipio, provincia, porcentaje_bonificacion, duracion_anos, condiciones)\nvalues\n"
            + ",\n".join(icio_rows)
            + "\non conflict (municipio, provincia) do update set\n"
            + "  porcentaje_bonificacion = excluded.porcentaje_bonificacion,\n"
            + "  duracion_anos = excluded.duracion_anos,\n"
            + "  condiciones = excluded.condiciones,\n"
            + "  updated_at = now();"
        )

    return "\n\n".join(parts) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Genera SQL de bonificaciones IBI/ICIO desde JSON estructurado.")
    parser.add_argument("--input", required=True, help="Ruta de JSON con extracciones IA")
    parser.add_argument("--output", default="data/queries/generated/bonificaciones_ibi_icio.generated.sql")
    args = parser.parse_args()

    records = load_records(args.input)
    sql = build_sql(records)

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(sql, encoding="utf-8")
    print(f"[OK] SQL generado: {out}")
    print(f"[OK] Registros entrada: {len(records)}")


if __name__ == "__main__":
    main()
