import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SOURCE_FILE = "data/queries/municipios_espana_dataset.sql";
const OUTPUT_DIR = "data/queries/municipios_parts";
const CHUNK_SIZE = Number(process.env.MUNICIPIOS_PART_SIZE ?? "25");

function pad(n: number): string {
  return String(n).padStart(2, "0");
}

function main() {
  const source = readFileSync(SOURCE_FILE, "utf8");

  const valuesMatch = source.match(/\)\s*values\s*([\s\S]*?)\s*on conflict/i);
  if (!valuesMatch) {
    throw new Error("Could not find VALUES block in source SQL file");
  }

  const rawValues = valuesMatch[1];
  const rows = rawValues
    .split(/\n/)
    .map((line) => line.trim())
    .filter((line) => line.startsWith("("));

  if (!rows.length) {
    throw new Error("No data rows found in source SQL file");
  }

  const tableHeader = `insert into municipios_dataset_es (\n  municipio, provincia, comunidad_autonoma, poblacion, latitud, longitud, codigo_postal, slug\n)\nvalues\n`;

  const conflictClause = `\non conflict (slug) do update set\n  municipio = excluded.municipio,\n  provincia = excluded.provincia,\n  comunidad_autonoma = excluded.comunidad_autonoma,\n  poblacion = excluded.poblacion,\n  latitud = excluded.latitud,\n  longitud = excluded.longitud,\n  codigo_postal = excluded.codigo_postal,\n  updated_at = now();\n`;

  mkdirSync(OUTPUT_DIR, { recursive: true });

  let part = 1;
  for (let i = 0; i < rows.length; i += CHUNK_SIZE) {
    const chunk = rows.slice(i, i + CHUNK_SIZE);

    const normalizedChunk = chunk.map((line, idx) => {
      const stripped = line.replace(/,$/, "");
      if (idx < chunk.length - 1) return `${stripped},`;
      return stripped;
    });

    const fileContent = [
      "-- Auto-generated by scripts/split-municipios-sql.ts",
      `-- Source: ${SOURCE_FILE}`,
      `-- Rows: ${chunk.length}`,
      "",
      tableHeader + normalizedChunk.join("\n") + conflictClause
    ].join("\n");

    const fileName = `municipios_espana_dataset_part_${pad(part)}.sql`;
    writeFileSync(join(OUTPUT_DIR, fileName), fileContent, "utf8");
    part += 1;
  }

  console.log(`Created ${part - 1} SQL part files in ${OUTPUT_DIR}`);
}

main();
