-- 20260418_bdns_solar_subsidies.sql
-- MIGRACIÓN PARA INTEGRACIÓN BDNS (Sistema Nacional de Publicidad de Subvenciones)

CREATE TABLE IF NOT EXISTS solar_subsidies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  municipality_slug TEXT NOT NULL,
  program_slug TEXT NOT NULL,
  program_name TEXT NOT NULL,
  amount_eur NUMERIC NOT NULL DEFAULT 0,
  source_url TEXT,
  status TEXT DEFAULT 'ABIERTA',
  fin_plazo DATE,
  bdns_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(municipality_slug, program_slug)
);

-- Índices obligatorios para SEO Programático (Velocidad de carga local)
CREATE INDEX IF NOT EXISTS idx_solar_subsidies_muni ON solar_subsidies(municipality_slug);
CREATE INDEX IF NOT EXISTS idx_solar_subsidies_prog ON solar_subsidies(program_slug);

-- RLS (Row Level Security) - Lectura pública, escritura bloqueada a service_role (API Cron)
ALTER TABLE solar_subsidies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read-only access to subsidies" 
ON solar_subsidies 
FOR SELECT USING (true);
